// Copyright (C) 2025-2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.

package pulsar

// mithril_rss.go — the DEALERLESS FIPS-204 signing key, generated by Replicated
// Secret Sharing (Mithril, ePrint 2026/013) instead of the trusted-dealer
// DealAlgShares. This is the file that walks past the pick-2 wall: a key
// produced with NO trusted dealer whose signatures verify byte-for-byte under
// unmodified cloudflare/circl mldsa65.Verify.
//
// Why it works (the wall, beaten). The vss/large-blinding dealerless DKG yields
// t = A·s1 + B·u with ‖B·u‖∞ ≈ q/2 — far outside S_η — so FindHint never fits a
// ±1 hint of weight ≤ ω and NO byte-stock-FIPS-204 signature exists. RSS keeps
// every share short: the key is the plain SUM of C(N,M) fresh χ_η subset
// secrets, so ‖s2‖∞ ≤ C(N,M)·η (≤ 80 for N≤6) — genuinely small. The BCC signer
// (bcc_sign.go) recovers the hint from the PUBLIC w' = A·z − c·t1·2^d exactly as
// the verifier does, so the small s2 only lowers the per-nonce acceptance rate;
// it never breaks verifiability. The committee combinatorics (subset
// enumeration, the (n,t) viability bound, the balanced reconstruction partition)
// come from github.com/luxfi/dkg/rss; the FIPS-204 arithmetic is pulsar's own
// circl-byte-identical lattice code, so the produced t1 is exactly what circl
// derives from (rho, s1, s2).
//
// Dealerless distribution. Each M-subset's short secret is sampled by that
// subset's LEADER (lowest-indexed member) from the leader's contributed entropy
// and replicated to the subset's members. No single party is a member of every
// subset (T ≥ 2), so no party ever holds the whole (s1, s2). Any T parties cover
// all subsets and reconstruct via the balanced partition; fewer than T are
// disjoint from a whole subset whose fresh short secret masks the key.

import (
	"fmt"
	"io"

	"github.com/luxfi/dkg/rss"
	"golang.org/x/crypto/sha3"
)

// mithrilSubsetSecret is one M-subset's short secret (s1^(S) ∈ R_q^L,
// s2^(S) ∈ R_q^K), coefficients in [q−η, q+η] (the pulsar χ_η representation).
// Replicated to every member of the subset and to no one else.
type mithrilSubsetSecret struct {
	mask uint64
	s1   polyVec // length L
	s2   polyVec // length K
}

// MithrilKey is a dealerless RSS threshold ML-DSA key. The public part (rho, t1,
// pub) is a genuine FIPS-204 public key; the private part is the per-party
// holdings (no single party holds all subsets). Sign by reconstructing the key
// material from any T parties' holdings (ReconstructKeyMaterial) and feeding it
// to the BCC signer.
type MithrilKey struct {
	Mode     Mode
	T, N     int
	rho      [32]byte
	a        []polyVec // K×L public matrix A = ExpandA(rho), NTT domain
	t1       polyVec   // high bits (published)
	t0       polyVec   // low bits (signer hint material)
	pub      []byte    // packed FIPS-204 public key: rho ‖ PackT1(t1)
	tr       [64]byte  // tr = SHAKE-256(pub)
	holdings []map[uint64]*mithrilSubsetSecret
	subsets  map[uint64]*mithrilSubsetSecret // every subset (keygen / audit view)
}

// Pub returns the packed FIPS-204 public key (rho ‖ PackT1(t1)).
func (mk *MithrilKey) Pub() []byte { return append([]byte(nil), mk.pub...) }

// Holdings returns the subset bitmasks held by party id (every subset that
// contains it), for the dealerless-distribution proofs.
func (mk *MithrilKey) Holdings(id int) []uint64 {
	out := make([]uint64, 0, len(mk.holdings[id]))
	for m := range mk.holdings[id] {
		out = append(out, m)
	}
	return out
}

// mithrilSubsetSeed derives a subset's 64-byte sampling seed from its leader's
// contributed entropy, domain-separated by the subset mask. Deterministic in
// (leaderSeed, mask): only the leader (and the members it replicates to) can
// derive the subset secret.
func mithrilSubsetSeed(leaderSeed []byte, mask uint64) *[64]byte {
	h := sha3.NewShake256()
	_, _ = h.Write([]byte("pulsar.mithril.rss.subset.v1"))
	_, _ = h.Write(leaderSeed)
	var mb [8]byte
	for i := 0; i < 8; i++ {
		mb[i] = byte(mask >> (8 * uint(i)))
	}
	_, _ = h.Write(mb[:])
	var seed [64]byte
	_, _ = h.Read(seed[:])
	return &seed
}

// mithrilRho derives the joint public seed rho from every party's contribution.
func mithrilRho(partySeeds [][]byte) [32]byte {
	h := sha3.NewShake256()
	_, _ = h.Write([]byte("pulsar.mithril.rss.rho.v1"))
	for _, s := range partySeeds {
		_, _ = h.Write(s)
	}
	var rho [32]byte
	_, _ = h.Read(rho[:])
	return rho
}

// accumulateSubset adds a subset secret into a running total and reduces it mod q
// IMMEDIATELY, per subset. This per-step reduction is mandatory, not cosmetic:
// every χ_η coefficient is stored in pulsar's [q−η, q+η] representation (≈ q ≈ 2²³),
// and poly.add is a raw uint32 add with no reduction (reduction is batched
// elsewhere in the NTT hot path). Summing all C(N,M) subset secrets without
// intermediate reduction would push the accumulator past 2³²: it overflows once
// C ≥ ⌊2³²/q⌋ = 512 — e.g. the owner default n=16,t=14 with C(16,3)=560 — wrapping
// the coefficient and corrupting the key into a large-secret (unsignable) wall
// key. Because reduction mod q is an additive homomorphism, reducing per subset
// yields the IDENTICAL short Σ_S secret as a single final reduction would for a
// small committee (so n≤8 results are unchanged), while keeping every intermediate
// accumulator below 2q ≪ 2³². total and add are equal-length (L or K) poly vectors.
func accumulateSubset(total, add polyVec) {
	for i := range total {
		total[i].add(&total[i], &add[i])
		total[i].normalize()
	}
}

// MithrilRSSKeygen runs the dealerless RSS DKG for an (T, N) committee at the
// given ML-DSA mode, driven by one contributed 32-byte seed per party. It is
// deterministic in (mode, t, n, partySeeds). Fail-closed outside the Mithril
// viability bound 2 ≤ T ≤ N ≤ rss.MaxParties.
func MithrilRSSKeygen(mode Mode, t, n int, partySeeds [][]byte) (*MithrilKey, error) {
	if err := rss.ValidateCommittee(t, n); err != nil {
		return nil, err
	}
	K, L, eta := modeShape(mode)
	if K == 0 {
		return nil, ErrUnknownMode
	}
	if len(partySeeds) != n {
		return nil, fmt.Errorf("pulsar: got %d party seeds, want N=%d", len(partySeeds), n)
	}
	for i, s := range partySeeds {
		if len(s) < 32 {
			return nil, fmt.Errorf("pulsar: party %d seed is %d bytes, want ≥32", i, len(s))
		}
	}

	mk := &MithrilKey{
		Mode: mode, T: t, N: n,
		rho:      mithrilRho(partySeeds),
		t0:       make(polyVec, K),
		t1:       make(polyVec, K),
		holdings: make([]map[uint64]*mithrilSubsetSecret, n),
		subsets:  map[uint64]*mithrilSubsetSecret{},
	}
	for i := range mk.holdings {
		mk.holdings[i] = map[uint64]*mithrilSubsetSecret{}
	}

	// A = ExpandA(rho), exactly as deriveKeyMaterial / circl.
	mk.a = make([]polyVec, K)
	for i := 0; i < K; i++ {
		mk.a[i] = make(polyVec, L)
		for j := 0; j < L; j++ {
			polyDeriveUniform(&mk.a[i][j], &mk.rho, uint16(i)<<8|uint16(j))
		}
	}

	// Per-subset short secret, sampled by the subset's leader; accumulate the
	// composite secret s1 = Σ_S s1^(S), s2 = Σ_S s2^(S).
	s1Tot := make(polyVec, L)
	s2Tot := make(polyVec, K)
	for _, mask := range rss.EnumerateSubsets(t, n) {
		leader := rss.LeaderOf(mask)
		seed := mithrilSubsetSeed(partySeeds[leader], mask)
		ss := &mithrilSubsetSecret{mask: mask, s1: make(polyVec, L), s2: make(polyVec, K)}
		for i := 0; i < L; i++ {
			polyDeriveUniformLeqEta(&ss.s1[i], seed, uint16(i), eta)
		}
		for i := 0; i < K; i++ {
			polyDeriveUniformLeqEta(&ss.s2[i], seed, uint16(i+L), eta)
		}
		mk.subsets[mask] = ss
		for _, member := range rss.SubsetMembers(mask, n) {
			mk.holdings[member][mask] = ss
		}
		// Reduce mod q PER SUBSET (accumulateSubset) — summing all C(N,M) subsets
		// raw would overflow the uint32 coefficient for a large committee.
		accumulateSubset(s1Tot, ss.s1)
		accumulateSubset(s2Tot, ss.s2)
	}

	// Public key t = A·s1 + s2, Power2Round → (t0, t1), pack pub, tr.
	computePublicKey(mk, s1Tot, s2Tot)
	return mk, nil
}

// computePublicKey fills mk.t0, mk.t1, mk.pub, mk.tr from the composite (s1, s2).
// Mirrors deriveKeyMaterial's t-computation with the proven circl-identical
// arithmetic, so the resulting t1 is exactly circl's for this (rho, s1, s2).
func computePublicKey(mk *MithrilKey, s1, s2 polyVec) {
	K, L, _ := modeShape(mk.Mode)
	s1Hat := make(polyVec, L)
	for i := 0; i < L; i++ {
		s1Hat[i] = s1[i]
		s1Hat[i].ntt()
	}
	t := make(polyVec, K)
	for i := 0; i < K; i++ {
		polyDotHat(&t[i], mk.a[i], s1Hat)
		t[i].reduceLe2Q()
		t[i].invNTT()
		t[i].add(&t[i], &s2[i])
		t[i].normalize()
		t[i].power2Round(&mk.t0[i], &mk.t1[i])
	}
	mk.pub = make([]byte, 32+320*K)
	copy(mk.pub[:32], mk.rho[:])
	for i := 0; i < K; i++ {
		polyPackT1(&mk.t1[i], mk.pub[32+320*i:32+320*(i+1)])
	}
	h := sha3.NewShake256()
	_, _ = h.Write(mk.pub)
	_, _ = h.Read(mk.tr[:])
}

// ReconstructKeyMaterial rebuilds the full FIPS-204 key material from any T
// active parties' holdings, summing each of the C(N,M) subset secrets exactly
// once via the balanced partition (rss.RSSRecover). This is the threshold-gated
// act that lets a quorum sign; the dealerless keygen never performs it. active
// must be a sorted, duplicate-free set of T party ids.
func (mk *MithrilKey) ReconstructKeyMaterial(active []int) (*mldsaKeyMaterial, error) {
	K, L, _ := modeShape(mk.Mode)
	part, err := rss.RSSRecover(active, mk.T, mk.N)
	if err != nil {
		return nil, err
	}
	s1 := make(polyVec, L)
	s2 := make(polyVec, K)
	for j, masks := range part {
		party := mk.holdings[active[j]]
		for _, mask := range masks {
			ss, ok := party[mask]
			if !ok {
				return nil, fmt.Errorf("pulsar: signer %d missing assigned subset 0b%b", active[j], mask)
			}
			// Reduce mod q PER SUBSET (accumulateSubset) — see ReconstructKeyMaterial.
			accumulateSubset(s1, ss.s1)
			accumulateSubset(s2, ss.s2)
		}
	}

	km := &mldsaKeyMaterial{rho: mk.rho, tr: mk.tr, s1: s1, s2: s2, pub: mk.pub}
	km.t0 = make(polyVec, K)
	km.t1 = make(polyVec, K)
	copy(km.t0, mk.t0)
	copy(km.t1, mk.t1)
	km.a = mk.a
	return km, nil
}

// Sign produces a byte-stock-FIPS-204 ML-DSA signature on (message, ctx) under
// the dealerless RSS group key, from any T active parties. It reconstructs the
// key material from the quorum's holdings (balanced partition), runs the BCC
// signer — whose hint is recovered from the PUBLIC w' = A·z − c·t1·2^d, so it
// emits NONE of c·s2 / c·t0 / r0 — and FAIL-CLOSED self-verifies the result
// against the FIPS-204 verifier before returning. The returned *Signature
// verifies under unmodified cloudflare/circl mldsa{65,87}.Verify.
//
// This is the threshold-gated SIGNING act: it requires a T-quorum and rebuilds
// the secret at the signing coordinator. The dealerless KEYGEN never does this —
// no party holds the full key at keygen. (A signing-time no-reconstruct variant
// is the Mithril 3-round hyperball protocol, where each party emits only its
// partial z_i = y_i + c·s_{1,I}; that is the signing-side hardening follow-up.)
func (mk *MithrilKey) Sign(active []int, message, ctx []byte, rng io.Reader, maxAttempts int) (*Signature, error) {
	km, err := mk.ReconstructKeyMaterial(active)
	if err != nil {
		return nil, err
	}
	sigBytes, _, err := bccSign(km, mk.Mode, message, ctx, rng, maxAttempts)
	if err != nil {
		return nil, fmt.Errorf("pulsar: mithril RSS sign: %w", err)
	}
	sig := &Signature{Mode: mk.Mode, Bytes: sigBytes}
	// Fail-closed: never emit a signature the FIPS-204 verifier rejects.
	params, err := ParamsFor(mk.Mode)
	if err != nil {
		return nil, err
	}
	pk := &PublicKey{Mode: mk.Mode, Bytes: mk.pub}
	if err := VerifyCtx(params, pk, message, ctx, sig); err != nil {
		return nil, fmt.Errorf("pulsar: mithril RSS sign self-verify failed (refusing to emit): %w", err)
	}
	return sig, nil
}
